version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build-deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: "16.13.0"
      - checkout
      - aws-cli/setup
      - eb/setup
        # installing frontend dependencies
      - run:
          name: Front-End Install
          command: |
            npm run front-end:install
        # building frontend
      - run:
          name: Front-End Build
          command: |
            npm run front-end:build
        # deploying frontend
      - run:
          name: Deploy UI
          command: |
            npm run front-end:deploy
        # installing backend dependencies
      - run:
          name: Back-End Install
          command: |
            npm run back-end:install
        # building backend
      - run:
          name: Back-End Build
          command: |
            npm run back-end:build
        # deploying backend
      - run:
          name: Deploy Server
          command: |
            npm run back-end:deploy
workflows:
  build-deploy:
    jobs:
      - build-deploy:
          filters:
            branches:
              only: main